[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[lint]
exclude_lints = [
    "mixed-case-variable",
    "mixed-case-function",
]
ignore = ["test/**/*"]

